language: "perl"

perl:
  - "5.14"
  - "5.10"

env:
  - COVERALLS=true
  - COVERALLS=false

sudo: false

addons:
  apt:
    packages:
    - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-rest.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - ln -s . ensembl-compara
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip
    - git clone --branch master --depth 1 https://github.com/samtools/tabix.git
    - cd tabix
    - make
    - cd perl
    - perl Makefile.PL
    - make && make install
    - cd ../../


install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile ./ensembl/
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl-rest/cpanfile ./ensembl-rest/
    - cpanm -v --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cp -f travisci/MultiTestDB.conf.travisci  modules/t/MultiTestDB.conf
    - cp -f ensembl-rest/travisci/MultiTestDB.conf.travisci ensembl-rest/t/MultiTestDB.conf

script: "./travisci/harness.sh"

# Get the matrix to only build coveralls support when on 5.10
matrix:
  exclude:
    - perl: "5.10"
      env: COVERALLS=true
    - perl: "5.14"
      env: COVERALLS=false

