os: linux
dist: trusty
language: generic

env:
  global:
    secure: bGSZASCtRCcE2VZ3u4hdvjh6CDHe+Uo3MR7B4eobSFFhZVjIN3/DKaGrQYprEeSIB/vb75rveyTheO3qe3lHwq71e18cBk2ulQA6/L0eUJYsoR3u2y7d9whu8dS97IoLzize6hItxJFP8TmRaJBtWqOixyWHNW72X/fKF1a192E=

addons:
  apt:
    packages:
    - graphviz

services:
  - mysql

cache:
  directories:
    - $HOME/deps

# Clone all repositories and setup the directory structure
before_install:
    - cpanm -nq local::lib
    - eval "$(perl -Mlocal::lib=${HOME}/deps)"
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-rest.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-funcgen.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-hive.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-taxonomy.git
    - ln -s . ensembl-compara
    - git clone --branch v1.6.x --depth 1 https://github.com/bioperl/bioperl-live
    - git clone --branch release-1-6-9 --depth 1 https://github.com/bioperl/bioperl-run
    - sed -i '/Bio::DB::HTS/d' ensembl-rest/cpanfile

# Setup the Perl dependencies and configuration
install:
    - cp -f travisci/MultiTestDB.conf.travisci  modules/t/MultiTestDB.conf
    - cp -f ensembl-rest/travisci/MultiTestDB.conf.travisci ensembl-rest/t/MultiTestDB.conf
    - cp -f ensembl/travisci/MultiTestDB.conf.travisci.mysql  ensembl/modules/t/MultiTestDB.conf
    - cpanm --quiet --installdeps --notest --cpanfile ensembl/cpanfile .
    - cpanm --quiet --installdeps --notest --cpanfile ensembl-rest/cpanfile .
    - cpanm --quiet --installdeps --notest --cpanfile ensembl-hive/cpanfile .
    - cpanm --quiet --installdeps --notest .
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

# Setup the MySQL server
before_script:
    - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

script: travis_wait 40 "./travisci/perl-unittest_harness.sh"

# What jobs to run and in which order
jobs:
  include:
    - language: perl
      perl: 5.30
      name: "Housekeeping (all languages)"
      script: env PERL5LIB=$PERL5LIB:$PWD/modules:$PWD/ensembl/modules:$PWD/ensembl-test/modules:$PWD/ensembl-io/modules prove -r ./travisci/all-housekeeping/

    - language: perl
      perl: 5.14
      name: "Perl unit tests on the minimum version"
      env: COVERALLS=false

    - language: perl
      perl: 5.30
      name: "Perl unit tests on the latest version, with code coverage"
      env: COVERALLS=true

    - language: perl
      perl: 5.30
      name: "Perl linter"
      script: ./travisci/perl-linter_harness.sh

    - language: python
      python: 3.6             # 3.8 is not available on Trusty builds
      name: "Python linter"
      before_install:
        - echo
      install:
        - pip install -r requirements.txt
      script: ./travisci/pylint_harness.sh

    - stage: "trigger dependent builds"
      before_install:
        - echo
      install:
        - echo
      script: ./travisci/trigger-dependent-build.sh

